### PR TITLE
WIP: run jobs with remote gRPC server

### PR DESCRIPTION
**Pull request by sercand**
As I described on this [comment](https://github.com/victorcoder/dkron/issues/78#issuecomment-240836423), this PR implements executing jobs via gRPC call.

### CODE REVIEW

**Comment by victorcoder** [comment]
Thanks for the contribution! Could you elaborate in the use case for this?

**Comment by sercand** [comment]
@victorcoder thanks for the quick response.
My motivation of this PR is I believe running jobs via bash script is powerful but also is limited. It requires dependent applications installed on the same host. If you're using docker you have to bundle them with the image. Also, it is not safe to execute another process at the same host. Safest way is running a task via the network. Http is another solution but it lacks type safety and standardization. Using gRPC provides type safety, all you need is the implement "dkron.v1.DkronExecutor" on a server. Also, you can use TLS to authenticate clients. GRPC now powers many distributed solutions like docker containerd/swarm-kit, etcd3, tensorflow, Google Bigtable.
To conclude, I believe implementing gRPC based job execution is imported for distributed dkron.

**Comment by victorcoder** [comment]
I don't want to sound like a show stopper but this change implies opening the job types issue and aside that I already have plans for this, I don't like the way it's implemented, adding a new property `grpc` to de job is not something that I want. It should be something more generic implemented in a more flexible fashion.

In case of running a task using docker you should call your scheduler API to start a task or call docker directly from the job command, run the job and exit.

I don't like to have a (listening server where you need to know the URL in advance) waiting to be calles to run some action specially using docker, doesn't seem like a good practice.

I wanted to let you know this before you put more work into it

**Comment by sercand** [comment]
I don't understand what do you mean by need to know the URL in advance. I am running Kubernetes cluster so the URL is like "email-sender.default". It's not that difficult, everything is a microservice inside the cluster. The difficult part is knowing locations of TLS cert files and whether it is using TLS or not.

**Comment by victorcoder** [comment]
@sercand the URL is not the main problem I see, as you said probably not a problem, on the other hand I don't like this implementation, I'm not saying it doesn't work but it's something related to job types and this must be designed somehow more generic.

With this PR we'll get command jobs and `grpc` jobs but what about other types of jobs?

I need to think on the job types topic a bit more before accepting PRs for extending job types.

In the meantime, refer to my previous comment: In case of running a task using docker you should call your scheduler API to start a task or call docker directly from the job command, run the job and exit.

**Comment by victorcoder** [comment]
Closing this at the moment, this will be addressed soon.

**Pull request closed without merging**
