### PR TITLE
Fix new jobs counting as failed in dashboard

### PR DESCRIPTION
**Pull request by yvanoers**
Fixes the third item mentioned in #535.
Not sure whether new assets_vfsdata.go and templates_vfsdata.go also need to be committed. If so, please let me know.

### CODE REVIEW

**Comment by yvanoers** [comment]
If you want me to port this to the v2.x branch, please let me know.

**Comment by victorcoder** [comment]
Porting this to v2 would be ❤️

**Comment by viperfx** [comment]
@yvanoers @victorcoder just curious guys - is out in a release? I see that it been merged to master, so curious if I could run this myself and test it locally?

**Comment by yvanoers** [comment]
Hi @viperfx,
RIght now, this is out only in v2 since v2.0.0-b2. I don't know what @victorcoder 's plans are for releasing v1.

**Comment by victorcoder** [comment]
@viperfx released in v1.2.5 https://github.com/distribworks/dkron/blob/master/CHANGELOG.md#125

**Pull request merged**
