### PR TITLE
LibKV authentication

### PR DESCRIPTION
**Pull request by seiffert**
In order to run dkron with an etcd cluster that is hosted somewhere else, we would like to use etcd authentication. I've [added this feature to libkv](https://github.com/docker/libkv/pull/121) and would like to add these configuration options to dkron as well.

The other libkv backends will get the same options in the future: https://github.com/docker/libkv/issues/124

What do you think, @victorcoder?

### CODE REVIEW

**Comment by victorcoder** [comment]
I followed your work in libkv @seiffert and it's awesome.

Just that we'll need a test for this.

**Comment by seiffert** [comment]
I agree :) I'll add one soon

**Comment by victorcoder** [comment]
@seiffert  ❤️ to add this

**Comment by seiffert** [comment]
I rebased the branch and will add a test now. Just to clarify: You mean a test for the configuration, right? So I would probably need to extend https://github.com/victorcoder/dkron/blob/f721d1c784c437d68cda286fe66a70d9ef60bd0e/dkron/agent_test.go#L331-L370, right?

**Comment by seiffert** [comment]
Sorry, I'm no longer working on this because I don't use dkron at work anymore. Should I just close this PR or would you like to take over from here?

**Comment by victorcoder** [comment]
Thanks @seiffert, yes I'll take care

**Pull request closed without merging**
