### PR TITLE
Add redis as storage backend

### PR DESCRIPTION
**Pull request by digitalcrab**
Hello guys,

First of all, thank you for the great software. We are thinking of giving a try ;)

One little issue we have is we don't wanna extend our infra having etcd or consul.
We have Redis running ad it would be nice to utilize it for dkron as well.

We noticed that `github.com/abronan/valkeyrie` has redis support.
And it works perfectly for us.

What do you think?
Thank you

### CODE REVIEW

**Comment by victorcoder** [comment]
Thanks for the work @digitalcrab, redis could be included but I can't offer deep testing. 

Given that a commercially supported version of Dkron is comming and I will offer support for etcd, I recommend you to use etcd in case you want to opt for the paid version.

**Comment by digitalcrab** [comment]
@victorcoder hello, thank you for the quick reply.
Branch rebased.

For us, it's a bit too early to think about the commercial version, but anyway thank you for the proposal. We gonna start using it next weeks and let's see how it goes.

**Comment by yuhui-lin** [comment]
@digitalcrab Hello, we are interested in Dkron with redis as backend. But I am pretty new to golang.
I checkout your `redis-backend` branch, uncomment redis in `docker-compose.yaml` and run containers.
I got this error:
`dkron_1   | time="2018-05-02T03:20:22Z" level=info msg="agent: Dkron agent starting" node=c5b3b5cbba1f
dkron_1   | time="2018-05-02T03:20:22Z" level=info msg="agent: joining: [dkron:8946] replay: true" node=c5b3b5cbba1f
dkron_1   | time="2018-05-02T03:20:22Z" level=info msg="agent: joined: 1 nodes" node=c5b3b5cbba1f
dkron_1   | time="2018-05-02T03:20:22Z" level=error msg="Backend storage not supported yet, please choose one of " node=c5b3b5cbba1f
dkron_1   | time="2018-05-02T03:20:22Z" level=debug msg="store: Backend config" backend=redis keyspace=dkron machines="[redis:6379]" node=c5b3b5cbba1f
dkron_1   | panic: runtime error: invalid memory address or nil pointer dereference
dkron_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xbb6bb9]
dkron_1   | 
dkron_1   | goroutine 1 [running]:
dkron_1   | github.com/victorcoder/dkron/vendor/github.com/victorcoder/dkron/dkron.NewStore(0x7fff499fae7f, 0x5, 0xc4202b9320, 0x1, 0x1, 0xc420384d80, 0xdfd55c, 0x5, 0x0, 0xc67180)
dkron_1   | 	/gopath/src/github.com/victorcoder/dkron/vendor/github.com/victorcoder/dkron/dkron/store.go:60 +0x3d9
`
I couldn't figure out why valkeyrie complained about redis backend. I would appreciate it if you could give me some hints

**Comment by digitalcrab** [comment]
@yuhui-lin Hello, have you tried to run `dep ensure` before starting docker-compose? Also, it would be useful to run `docker-compose down` before to reset old containers.

**Comment by yuhui-lin** [comment]
@digitalcrab thanks for your help. I think the error was because I didn't put the project under `github.com/victorcoder`. it's working now.

**Comment by victorcoder** [comment]
@digitalcrab could you merge again `v0.10.0` and test it with some jobs?

**Comment by digitalcrab** [comment]
@victorcoder rebase done, tested as well

**Comment by koolay** [comment]
@digitalcrab 
The leadership is not worked with redis backend.   There is no new leader selected when leader was lost. 

error log:   `watchLoop in Watch err:Key not found in store`

**Comment by digitalcrab** [comment]
@koolay thank you for the report. The only thing that this PR doesn't change the mechanism of the leadership election. It's just yet another store behind the store abstraction. Anyway, I'll check.

**Pull request merged**
