### PR TITLE
Update executor support error log instead of rpc error only

### PR DESCRIPTION
**Pull request by tengattack**
Fix executor run command failed but only rpc error status return & store.

### CODE REVIEW

**Comment by tengattack** [comment]
Previous log like this:
```
rpc error: code = Unknown desc = exit status 1
```

After patching this PR, we have detail log:
```
exit status 1
firstline
```

**Comment by tengattack** [comment]
Do you have a time to take a look? @victorcoder 
I think the error logs would be the key to identified the issue came from.

**Comment by victorcoder** [comment]
Thanks @tengattack I was doubtful about doing this in the first place, but I like this implementation.
Could you merge or rebase master here and generate the proto file just to make sure it's in sync?

**Comment by tengattack** [comment]
Yep

**Pull request closed without merging**
