### PR TITLE
Add support for passing payload to command STDIN

### PR DESCRIPTION
**Pull request by gustavosbarreto**

### CODE REVIEW

**Comment by victorcoder** [comment]
Thanks @gustavosbarreto, could you rebase with v0.10.0?

**Comment by gustavosbarreto** [comment]
@victorcoder I'm not sure how to do it on v0.10.0.
The ```payload``` should be placed into ```Job``` struct or into specific ```executor_config```?

**Comment by victorcoder** [comment]
@gustavosbarreto good question, as you can see, shell options in `Job` structure is being deprecated in favor of the `shell-executor` plugin so, we should add the `Payload` handling in the plugin not in the `Job` structure.

**Comment by otavio** [comment]
@victorcoder, @gustavosbarreto and I were discussing it and we'll follow your advice to add it inside the plugin however we noticed that the protobuf generated code seems outdated in 0.10.0 branch.

Could you take a look?

**Comment by victorcoder** [comment]
@otavio What do you mean outdated? you can try to run `protoc -I proto/ proto/executor.proto --go_out=plugins=grpc:dkron/` no changes on my side, can you check?

**Comment by victorcoder** [comment]
@otavio are you still on this? should I take over?

**Comment by otavio** [comment]
Yes please take it over; we ended not using it in our service as we replaced it with machinary.

**Pull request merged**
